#pragma once
#define TXT_NODE_PARAFIND	"FindPara" 
#define SUBNODE_ANGSTART	"AngleStart"
#define SUBNODE_ANGEXTENT	"AngleExtent"
#define SUBNODE_MINSCORE	"MinScore"
#define SUBNODE_NUMMATCHES	"NumMatches"
#define PATH_FIND_PARA  "FindPara.ini"
#define SUBNODE_MAXOVERLAP	"MaxOverlap"
#define SUBNODE_SUBPIXEL	"SubPixel"
#define SUBNODE_MODELLEVELS	"ModelLevels"
#define SUBNODE_NUMLEVELS	"NumLevels"
#define SUBNODE_GREEDINESS	"Greediness"
#define SUBNODE_MODEL_X "ModelX"
#define SUBNODE_MODEL_Y "ModelY"
#define SUBNODE_MODEL_A "ModelAngle"

#define PATH_MODELFILE "Model.shm"
#define SUBNODE_MODELRECT_ROW "Row"
#define SUBNODE_MODELRECT_COL "Col"
#define SUBNODE_MODELRECT_PHI "Phi"
#define SUBNODE_MODELRECT_LEN1 "Len1"
#define SUBNODE_MODELRECT_LEN2 "Len2"

#define TXT_NODE_AREA_MODEL "ModelDetectArea"
#define TXT_NODE_AREA_BARCODE "BarcodeDetectArea"
#define SUBNODE_ROW1 "row1"
#define SUBNODE_COL1 "col1"
#define SUBNODE_ROW2 "row2"
#define SUBNODE_COL2 "col2"
#define SUBNODE_VALID "valid"
#define PATH_DETECTAREA "DetectArea.ini"

#define TXT_NODE_CAM "Camera"
#define SUBNODE_EXP_TIME "ExposureTime"

//标定
#define PATH_CALIBRATE "Calib.ini"
#define NODE_IMAGE_PT "Image"
#define NODE_WORLD_PT "World"
#define NODE_AFFINE   "Affine"
#define NODE_ROT	  "Rotate"
#define SUBNODE_PT_X1 "X1"
#define SUBNODE_PT_X2 "X2"
#define SUBNODE_PT_X3 "X3"
#define SUBNODE_PT_X4 "X4"
#define SUBNODE_PT_X5 "X5"
#define SUBNODE_PT_X6 "X6"
#define SUBNODE_PT_X7 "X7"
#define SUBNODE_PT_X8 "X8"
#define SUBNODE_PT_X9 "X9"

#define SUBNODE_PT_Y1 "Y1"
#define SUBNODE_PT_Y2 "Y2"
#define SUBNODE_PT_Y3 "Y3"
#define SUBNODE_PT_Y4 "Y4"
#define SUBNODE_PT_Y5 "Y5"
#define SUBNODE_PT_Y6 "Y6"
#define SUBNODE_PT_Y7 "Y7"
#define SUBNODE_PT_Y8 "Y8"
#define SUBNODE_PT_Y9 "Y9"
//仿射变换矩阵
#define SUBNODE_AFFINE_P1 "P1"
#define SUBNODE_AFFINE_P2 "P2"
#define SUBNODE_AFFINE_P3 "P3"
#define SUBNODE_AFFINE_P4 "P4"
#define SUBNODE_AFFINE_P5 "P5"
#define SUBNODE_AFFINE_P6 "P6"

//旋转标定
#define SUBNODE_ROT_CENT_X "CentX"
#define SUBNODE_ROT_CENT_Y "CentY"
#define SUBNODE_ROT_RADIUS "Radius"

